apiVersion: v1
kind: Service
metadata:
  name: workspacekit
  namespace: workspacekit
  labels:
    app: workspacekit
spec:
  type: NodePort
  selector:
    app: workspacekit
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
      protocol: TCP
